name: "Stay Nest deployment pipeline"
on:
  push:
    branches:
      - main
      - staging

env:
  PORT: 3000
  NODE_ENV: production
jobs:
  test:
    uses: ./.github/workflows/testing.yaml
    with:
      server_port: 3000
      database_username: root
      database_password: example

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: |
          echo "Deployment started"
          echo "====environmental variables====="
          echo "PORT ${{env.PORT}}"
          echo "NODE_ENV $NODE_ENV"
    




